{{- $g := .Values.global -}}
{{- if and $g.workloadIdentity.enabled $g.keyVault.name }}
{{- range $name, $comp := .Values.components }}
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: spc-{{ $name }}
spec:
  provider: azure
  secretObjects:
  - secretName: {{ $name }}-kv-secrets
    type: Opaque
    data:
    - objectName: sql-connection-string
      key: SQL_CONNECTION_STRING
    - objectName: cosmos-endpoint
      key: COSMOS_ENDPOINT
    - objectName: cosmos-primary-key
      key: COSMOS_PRIMARY_KEY
    - objectName: redis-primary-connection-string
      key: REDIS_CONNECTION_STRING
    - objectName: application-insights-connection-string
      key: APPINSIGHTS_CONNECTION_STRING
    - objectName: appconfig-endpoint
      key: APPCONFIG_ENDPOINT
    {{- if $.Values.b2c.webClientSecretKey }}
    - objectName: {{ $.Values.b2c.webClientSecretKey }}
      key: B2C_WEB_CLIENT_SECRET
    {{- end }}
  parameters:
    usePodIdentity: "false"
    clientID: "{{ $g.workloadIdentity.clientId }}"
    keyvaultName: "{{ $g.keyVault.name }}"
    cloudName: ""
    tenantId: "{{ $g.tenantId }}"
    objects: |
      array:
        - | {objectName: sql-connection-string, objectType: secret}
        - | {objectName: cosmos-endpoint, objectType: secret}
        - | {objectName: cosmos-primary-key, objectType: secret}
        - | {objectName: redis-primary-connection-string, objectType: secret}
        - | {objectName: application-insights-connection-string, objectType: secret}
        - | {objectName: appconfig-endpoint, objectType: secret}
        {{- if $.Values.b2c.webClientSecretKey }}
        - | {objectName: {{ $.Values.b2c.webClientSecretKey }}, objectType: secret}
        {{- end }}
---
{{- end }}
{{- end }}
