{{- $g := .Values.global -}}
{{- range $name, $comp := .Values.components }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $comp.sa }}
  annotations:
    {{- if $g.workloadIdentity.enabled }}
    azure.workload.identity/client-id: "{{ $g.workloadIdentity.clientId }}"
    {{- if $g.tenantId }}
    azure.workload.identity/tenant-id: "{{ $g.tenantId }}"
    {{- end }}
    {{- end }}
---
{{- end }}
